name: Container
on: [pull_request, push]
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker login -u rfratto -p "${{ secrets.DOCKER_PASS }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make container
        run: OSXCROSS_SDK_URL="${{ secrets.OSXCROSS_SDK_URL }}" make build
      - name: Push container
        run: make push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
